### ISSUE TITLE
MVP Feature: User can search for restaurants by name

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for restaurants by name
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click a search bar where they can type in a restaurant’s name and a city or zip code. When they search, the results will be shown to the user. The results will include the restaurant’s name, photo(s), address, phone number, 3 reviews, and if they are currently open right now.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Search Mobile](https://user-images.githubusercontent.com/82472092/126210323-17f0aa5f-6e2a-4aa0-b213-f1c41e50996a.png)
![Search Desktop](https://user-images.githubusercontent.com/82472092/126210340-b42252d9-136a-4946-8c2d-d35ef01ce58c.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET request to the yelp api
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to make the header for the home page
- [x] In the header, add the nav bar icon
- [x] In the header, add the logo
- [x] In the header, create a form 
- [x] Create an input type equal to text and name equal to name 
- [x] Add the search icon into the input field
- [x] Create an input type equal to text, name equal to location and required
- [x] Create a handleChange method that will update the state with the value of the fields
- [x] Set the onChange prop equal to the handleChange method
- [x] Make sure that the values are being stored when the user is typing into the form
- [x] When the form is submitted, prevent the page from being refreshed
- [x] Take the stored data in the state and call the fetch method to make a GET request to the API
- [x] If the API returns an error, throw the error and tell the user that the search was invalid
- [x] If the API returns data, set the state with a property equal to the data returned
- [x] With the data stored in the state, change the hash location to the search result page
- [x] On the search result page, make a title that says `Best ${user input} nearby}`
- [x] In the search result page, render the restaurants in their own containers
- [x] For each restaurant, include the photo, name, stars, review count, price category, food category, and address
- [x] Style the page to look like the wireframe

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
