### ISSUE TITLE
MVP Feature: User can view the details of a search result

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of a search result
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on a search result which will show more information about the restaurant including if they are open or not, phone number, reviews and hours of operation.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Search Result Mobile](https://user-images.githubusercontent.com/82472092/126837672-10c714ca-f6c0-4238-87ce-6fcbbdc48cd9.png)
![Search Result Desktop](https://user-images.githubusercontent.com/82472092/126837683-c67ac475-28b6-4ae9-b7f0-e43731c42157.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET request from the route '/api/business'
- [x] With businessId passed to the server, send a GET request to the YELP API to get the reviews of the business
- [x] Send the reviews back to the client
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] For each li element in the search results list wrap it in an <a> and set the href to {`#details?businessId={businessId}`}
- [x] In the function get the businessId property of the li to get the unique Id provided by yelp
- [x] Use that business Id and make a GET request to the API passing in the Id as a parameter
- [x] When the API sends a response, store the response in the state
- [x] Pass down the state to the details component
- [x] In the business component, style the page to look like the wireframe
- [x] Add a home button which will take the user back to the home page where the search bar and results are displayed

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
