### ISSUE TITLE
MVP Feature: User can search for restaurants by geolocation

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for restaurants by geolocation.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can accept a prompt that will ask if the app can use their geolocation. If accepted, the search will default to the location given. All results will be close to the location.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Search Mobile](https://user-images.githubusercontent.com/82472092/126211911-e03c5c8e-3669-438a-992c-4c507ef96314.png)
![Search Result Mobile](https://user-images.githubusercontent.com/82472092/126211920-a42d5226-5bc8-458d-a45a-3295cad5cbaa.png)
![Search Desktop](https://user-images.githubusercontent.com/82472092/126211929-048e0814-49e4-41b7-969a-8479e0894b9c.png)
![Search Result Desktop](https://user-images.githubusercontent.com/82472092/126211933-37aec237-7c30-4650-a638-8304665ab698.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET requests for the '/api/location' route
- [x] In that route, send a GET request with the latitude and longitude provided by the user using Google Maps reverse geocoding API
- [x] Handle errors from the API
- [x] If there are no errors and the GET request was successful, get the address (mainly zip code) from the response and send it as the response
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] In the app.jsx component create a property in the state named geolocation and set it to null 
- [x] In the app.jsx component, define the componentDidMount method
- [x] In the componentDidMount method, create a conditional to check if the geolocation property of the navigator object exists to see if it is supported in the user's browser
- [x] If the property does exist, call the getCurrentPosition of the geolocation property of the navigator object with 2 callback functions as arguments to handle the success and error. 
- [x] In the success function definition, destructor the latitude and longitude properties from the coords property of the position object
- [x] In the same success function, send a request to the server with the route '/api/location'
- [x] If the server responds with a successful address, store it in the location property of the state object
- [x] Pass the state location property down to the search-form component
- [x] In the search form component, check to see if the location property exists
- [x] If it doesn't exist, don't autofill the input field
- [x] If the property does exist, set the location property of the state object in search-form.jsx so that the value will be filled whenever the user wants to search. 

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
