### ISSUE TITLE
MVP Feature: User can create a Collection (favs, romantic, family, etc)

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a Collection (favs, romantic, family, etc)
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click on the navbar button on the top left of the screen and an app drawer will open with the option to create a new Collection. If the user clicks on that option, it will take them to a new page to create a Collection with a name.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Create Collection Modal Mobile](https://user-images.githubusercontent.com/82472092/126212567-32d23e62-d135-4213-ae7f-f6b030bac4fe.png)
![Create Collection Page Mobile](https://user-images.githubusercontent.com/82472092/126212570-e1c2131c-8b8c-49c1-9ee6-bca9e21bf246.png)
![Create Collection Modal Desktop](https://user-images.githubusercontent.com/82472092/126212572-614dcce8-c495-4134-b4ef-70b970a69690.png)
![Create Collection Page Desktop](https://user-images.githubusercontent.com/82472092/126212575-a312b554-1882-44e2-bc98-6b0f92425bac.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have a Collections table
- [x] Update `data.sql` to have a Collection named Favorites as default

### ☁️ Server

- [x] Update `server/index.js` to handle POST requests for '/api/newCollection'
- [x] Get the name of the Collection from req.body
- [x] Query the database using SQL and the parameters to prevent sql injection
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a 'new-collection' page that has a form to enter a name for a Collection
- [x] Update the navbar icon to open an app drawer when clicked
- [x] Inside the app drawer, create a link named 'create a new collection' that will take the user to the new-collection page
- [x] When the form in new-collection is submitted take the value of the form and send a POST request to '/api/newCollection'
- [x] Check the database to see if the Collection has been made

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
