### ISSUE TITLE
MVP Feature: User can add a restaurant to a Collection

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add a restaurant to a Collection
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

On a search result, there will be a bookmark icon that will allow the user to add a restaurant to a Collection that they have created
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add to Collection Mobile](https://user-images.githubusercontent.com/82472092/126212884-92d10800-0ebf-41ba-81de-743e5a82ddd6.png)
![Add to Collection Desktop](https://user-images.githubusercontent.com/82472092/126212890-9b89ff39-3360-4b32-a8ad-c2c06afcf0c8.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to have a table for restaurants

### ☁️ Server

- [x] Update `server/index.js` to handle POST requests to '/api/restaurant'
- [x] Get the collectionId and restaurantId from the req.body
- [x] Query the database and add the restaurant into the database using the given collectionId and restaurantId
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Add a bookmark icon to the details page so that the user can also save a restaurant from the details page
- [x] Define a function named addRestaurant that will open the appDrawer and show a list of current collections that the user has at the moment
- [x] Set the selectedRestaurant property of the state to the value of the businessId
- [x] Set the saving state of the app to true
- [x] When the saving property of the state of the app is true, the button rendered next to the collection should be the save button
- [x] When the saving property is false, there should be no button next to the collection container
- [x] When the save button is clicked, store the collectionId in the selectedCollection property of the state
- [x] Also when the save button is clicked send a fetch (post) request to the '/api/restaurant' route with the collectionId and restaurantId in the body of the request
- [x] Clear the state for the selectedRestaurant and selectedCollection and set the saving property to false
- [x] Make sure that the save button doesn't show when you open the app drawer when you're not saving a restaurant

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
