### ISSUE TITLE
MVP Feature: User can view their Collections

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their Collections
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to open the app drawer and see a list of their collections. Each collection will be clickable. If the user clicks on a collection, it will take them to another page which will show which restaurants are in that selected collection.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![View Collection Mobile](https://user-images.githubusercontent.com/82472092/126213106-bd19d297-48ca-4a82-8b3e-30237a9c5533.png)
![View Collection Desktop](https://user-images.githubusercontent.com/82472092/126213111-352bdf51-6466-4ed8-b894-56b90212174c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to handle GET request from '/api/restaurants'
- [x] Get the collectionId from the req.query
- [x] Query the database to select json from the restaurants table where the collectionId is equal to the given one
- [x] Return the response from the query
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update collection-list component to have anchor tags around each collection which will redirect the user to '#collection?collectionId=${}'
- [x] Create a collection page the includes the name of the collection and list of all the restaurants in that collection
- [x] When the collection page mounts, send a GET request to '/api/restaurants' with the collectionId in the URL params
- [x] When the response is given from the server, set the response to the value for the collections property of the state.
- [x] In the render method, map through the collections property and render them as li elements.
- [x] Return a ul element with the return of the map method as the children

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
