### ISSUE TITLE
MVP Feature: User can get a random restaurant from a Collection

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can get a random restaurant from a Collection
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to click a random button on the collection page that will choose a restaurant in that collection and display it to the user.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Random Mobile](https://user-images.githubusercontent.com/82472092/126217239-87493a27-81e9-4acb-8cb0-409f75a084d8.png)
![Random Selection Mobile](https://user-images.githubusercontent.com/82472092/126217245-aafb0273-8a3c-41bf-8ffe-ff7136c2873d.png)
![Random Desktop](https://user-images.githubusercontent.com/82472092/126217253-43ff3711-6c54-4421-abf7-bdd01c00c8c2.png)
![Random Selection Desktop](https://user-images.githubusercontent.com/82472092/126217259-8aea0628-84a2-4d09-8e48-a32c4f49385a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] In the AppDrawer component, add the random icon to the top right corner
- [x] Add a conditional where the icon will only show if the route.path is 'collection'
- [x] Define a function that will take all the restaurants in the collection and pick one for the user
- [x] In the function, call Math.random() and multiply it by the length of the array of restaurants
- [x] With the results of Math.random() being multiplied, pass it into Math.floor()
- [x] Use the result of Math.floor() as the index to select the restaurant
- [x] Create a modal that will display the selected restaurant

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
