### ISSUE TITLE
MVP Feature: User can see the distance to a restaurant on a map

### ISSUE THREAD

**Issue by mosesr-kim** [mosesr-kim/what-to-eat#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the distance to a restaurant on a map
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to input an origin and destination to see the distance/route from point A to B
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Search Result Mobile](https://user-images.githubusercontent.com/82472092/126217347-4ea5b047-07a4-427d-b17e-1dad75307967.png)
![Search Result Desktop](https://user-images.githubusercontent.com/82472092/126217350-5e1d11c9-a663-48f2-9a50-ecf9bbe5c018.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a map.jsx component
- [x] In the map.jsx component, import GoogleMap, LoadScript, DirectionsService, and DirectionsRenderer from the @react-google-maps/api package from npm
- [x] Create a class with the state of response set to null, travel mode to driving, origin to an empty string, and destination to an empty string
- [x] Make a react controlled form that takes the users inputs and stores it in the state for origin and destination
- [x] Wrap the LoadScript with the googleMapsApiKey prop and the value of the API key from the env file
- [x] In the GoogleMap element, set the zoom, center, height, and width. The width should be 100%
- [x] Pass in the destination, origin, and travelMode to the DirectionsService element
- [x] Pass in the response to the DirectionsRenderer

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
